set -euo pipefail

# Proves tools/check-verification-metadata-pins detects a version that a security pin
# has superseded but which is still recorded in gradle/verification-metadata.xml.
#
# The gate exists because `./gradlew --write-verification-metadata` only ever APPENDS.
# Nothing in the Gradle side of this ever removes an entry, so a version that has been
# pinned away stays recorded — and osv-scanner (which OSSF Scorecard's Vulnerabilities
# check runs over the checkout) reads this file as a dependency manifest. That is how the
# repo scored 17 vulnerabilities at a commit where all 17 were already pinned away.
#
# The fixture builds a synthetic two-file repo rather than copying the real 344 KB
# metadata: the contract under test is "a recorded version that disagrees with its pin is
# a failure", which needs exactly one pinned module to demonstrate.

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

mkdir -p "$tmp/tools" "$tmp/gradle"
cp "$REPO_ROOT/tools/check-verification-metadata-pins" "$tmp/tools/"

write_catalog() {
  cat > "$tmp/gradle/libs.versions.toml" <<'TOML'
[versions]
httpclient = "4.5.14"
bouncycastle = "1.84"
jackson = "2.18.9"
jose4j = "0.9.6"
jdom2 = "2.0.6.1"
commons-lang3 = "3.18.0"
opentelemetry = "1.62.0"

[libraries]
bouncycastle-prov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
bouncycastle-pkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jose4j = { module = "org.bitbucket.b_c:jose4j", version.ref = "jose4j" }
jdom2 = { module = "org.jdom:jdom2", version.ref = "jdom2" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "httpclient" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry" }
TOML
}

# $1 = extra component XML injected before </components>
write_metadata() {
  cat > "$tmp/gradle/verification-metadata.xml" <<XML
<?xml version="1.0" encoding="UTF-8"?>
<verification-metadata>
   <configuration>
      <verify-metadata>true</verify-metadata>
   </configuration>
   <components>
      <component group="org.apache.httpcomponents" name="httpclient" version="4.5.14">
         <artifact name="httpclient-4.5.14.jar">
            <sha256 value="aaaa" origin="Generated by Gradle"/>
         </artifact>
      </component>
      <component group="org.jetbrains.kotlin" name="kotlin-stdlib" version="2.4.10">
         <artifact name="kotlin-stdlib-2.4.10.jar">
            <sha256 value="bbbb" origin="Generated by Gradle"/>
         </artifact>
      </component>
${1:-}
   </components>
</verification-metadata>
XML
}

check() { (cd "$tmp" && tools/check-verification-metadata-pins "$@"); }

write_catalog

if [ "$CASE_KIND" = "compliant" ]; then
  # Only the pinned version recorded, plus an unrelated module the gate must ignore.
  write_metadata ""
  check
  exit 0
fi

# --- violation scenarios (self-judging) ---

STALE_HTTPCLIENT='      <component group="org.apache.httpcomponents" name="httpclient" version="4.5.6">
         <artifact name="httpclient-4.5.6.jar">
            <sha256 value="cccc" origin="Generated by Gradle"/>
         </artifact>
      </component>'

# 1. The shape this gate exists for: a superseded version recorded alongside the pin.
write_metadata "$STALE_HTTPCLIENT"
if check >/dev/null 2>&1; then
  echo "FAIL-OPEN: a superseded httpclient 4.5.6 entry passed" >&2
  exit 0
fi

# 2. --prune must actually remove it AND leave the pinned entry intact. A fixer that
#    deleted everything, or nothing, would still make scenario 1 look fixed.
write_metadata "$STALE_HTTPCLIENT"
check --prune >/dev/null 2>&1
if ! check >/dev/null 2>&1; then
  echo "FAIL: --prune did not clear the violation" >&2
  exit 0
fi
if ! grep -q 'name="httpclient" version="4.5.14"' "$tmp/gradle/verification-metadata.xml"; then
  echo "FAIL: --prune removed the PINNED entry, not just the stale one" >&2
  exit 0
fi
if ! grep -q 'name="kotlin-stdlib"' "$tmp/gradle/verification-metadata.xml"; then
  echo "FAIL: --prune removed an unrelated, unpinned module" >&2
  exit 0
fi

# 3. A different pinned module — proves the check is driven by the catalog, not by a
#    hardcoded httpclient special case.
write_metadata '      <component group="org.bouncycastle" name="bcprov-jdk18on" version="1.79">
         <artifact name="bcprov-jdk18on-1.79.jar">
            <sha256 value="dddd" origin="Generated by Gradle"/>
         </artifact>
      </component>'
if check >/dev/null 2>&1; then
  echo "FAIL-OPEN: a superseded bcprov 1.79 entry passed" >&2
  exit 0
fi

# 4. Zero-scan guard: a file the parser cannot read must not report OK. This gate passes
#    by finding nothing, so unreadable and clean have to be distinguishable.
write_metadata ""
sed -i 's/<component /<COMPONENT /g' "$tmp/gradle/verification-metadata.xml"
if check >/dev/null 2>&1; then
  echo "FAIL-OPEN: a metadata file with zero parseable components passed" >&2
  exit 0
fi

# 5. Fail-closed on a catalog that lost a pin: dropping the alias must not silently
#    shrink the checked set to the ones that happen to remain.
write_metadata "$STALE_HTTPCLIENT"
grep -v '^httpclient = ' "$tmp/gradle/libs.versions.toml" > "$tmp/c.toml"
mv "$tmp/c.toml" "$tmp/gradle/libs.versions.toml"
if check >/dev/null 2>&1; then
  echo "FAIL-OPEN: a catalog missing the httpclient library alias passed" >&2
  exit 0
fi

exit 1
